"""Final autogen

Revision ID: 686a782749fd
Revises: 5b488eedcc07
Create Date: 2022-11-23 15:44:16.812424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686a782749fd'
down_revision = '5b488eedcc07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
